# Generated by Django 4.0.3 on 2022-03-06 17:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VictimUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_adhar', models.CharField(max_length=50)),
                ('category_crime', models.CharField(choices=[('CP', 'Child Pornography'), ('CB', 'Cyber Bullying'), ('P', 'Phishing'), ('OJF', 'Online Job Fraud'), ('V', 'Vishing'), ('Sm', 'Smishing'), ('S', 'Sexting'), ('P', 'Phishing'), ('SimSS', 'SIM Swap Scam'), ('Sp', 'Spamming'), ('R', 'Ransomware'), ('DB', 'Data Breach'), ('DoS', 'Denial Services of Attack'), ('VWM', 'Viruses,Worms,and Trojans')], max_length=10)),
                ('screenshot', models.ImageField(upload_to='screenshot')),
                ('suspected_person', models.CharField(max_length=50)),
                ('date_crime', models.DateTimeField()),
                ('suspected_email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=12)),
                ('suspected_mobile', models.CharField(max_length=12)),
                ('crime_source', models.CharField(max_length=100)),
                ('id_usedby_criminal', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
