# Generated by Django 4.0.3 on 2022-03-22 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='victimuser',
            old_name='screenshots',
            new_name='screenshots_obj',
        ),
    ]
