# Generated by Django 4.0.3 on 2022-03-06 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_victimuser_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='victimuser',
            name='user',
        ),
    ]
