# Generated by Django 4.0.3 on 2022-03-22 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_screenshots_victimuser_screenshots_obj'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='victimuser',
            name='screenshots_obj',
        ),
        migrations.AddField(
            model_name='screenshots',
            name='victimuser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.victimuser'),
        ),
    ]
