# Generated by Django 4.0.3 on 2022-03-22 18:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0003_remove_victimuser_screenshots_obj_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VictimUser',
            new_name='Report',
        ),
    ]
