# Generated by Django 4.0.3 on 2022-03-25 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_report_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='reason_for_reporting',
            new_name='reason_for_delay_reporting',
        ),
        migrations.AlterField(
            model_name='report',
            name='suspected_mobile',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
